version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'codegile-intern'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'codegileintern'
      # You can use whatever password you like
      MYSQL_PASSWORD: '12345678'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '5306:3306'
    expose:
      # Opens port 5306 on the container
      - '5306'
      # Where our data will be persisted
    volumes:
      - codegile-intern-db:/var/lib/mysql
# Names our volume
volumes:
  codegile-intern-db:
